name:                chinese-calendar
version:             0.1.0.0
github:              "FroskyArr/chinese-calendar"
license:             BSD3
author:              "FroskyArr"
maintainer:          "FroskyArr <me@frost.moe>"
copyright:           "2021 FroskyArr"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Chinese calendar
category:            Time
description:         Please see the README on GitHub at <https://github.com/FroskyArr/chinese-calendar#readme>

dependencies:
- base >= 4.7 && < 5
- bits
- bytes
- bytestring
- template-haskell
- th-lift-instances
- time
- vector

library:
  source-dirs: src
